### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by durd** [Swiftnesses/com.plex.notify#4]
Hi,

I'm experiencing errors logging in to my PMS with Plex Notify.
Whichever credentials i fill in it's the same error:
```-------------------------------------------------
[INITIALISE] Please wait...
[START] Plex notify starting...
[CREDENTIALS] Plex notify retrieving credentials...
[LOGIN] Plex notify attempting login...
[ERROR] Plex notify error: { Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' }
```

Any ideas?
Thanks!

**Comment by durd** [comment]
Fixed it, Plex Network settings was set to require secure connections.
The Plex-API that this app uses has https disabled by default. Thus no connections were allowed.

I tried adding https to the app, but the name in the certificate that Plex announces does not match your server or IP-address. Additionally, Plex uses a self-signed certificate, Homey would have to trust that root to validate the certificate.

If possible, it would be great if HTTPS could be enabled.

**Comment by xeor** [comment]
How did you get the logs? I'm trying the `Homey Logger` app, but it's popup function doesn't quite work, so I'm stuck with the in-homey-app view :( Any other way to get it?

I am also using https-only in my plex, so I might have the same problem as you. It's a long story for them, but plex uses certificates on your local install signed by `DigiCert`. Plex have a deal with them to issue sub-certs to adresses like `*.abclonghashhere.plex.direct` via an intermidiate cert that plex owns. In other words.. The certificate problem is already taking care of.

I found that the easiest way to see the url with the valid cert is to go to plex.tv, then open the debug toolbar and look for `plex.direct` requests.. You will find one that looks something like `10-1-2-3.longhashhere.plex.direct`.

**Comment by durd** [comment]
You'll need a *nix system that can access your Homey over the network. I'd suggest a debian virtualbox or raspbian rpi.
Once you've got that, follow this [guide](https://forum.athom.com/discussion/1448/how-to-cli-install-method) to install some Athom developer tools. The whole thread is good, so read through it.
After your done with that, gitclone this app to that system and run it with the Athom developer tool.

The tool will uninstall any version you already have running on your Homey, but it will keep the settings after uninstall. One can change the settings while the app is running in the cli. That is also where you will see the logs for the app.
It's kinda like loading and running the app from the side, sideloading :)

I saw some of those addresses around the logs I think, then I saw the whole format on the Internet somewhere, but I haven't tried anything with Homey yet. If you figure it out, please do add a comment here :)

**Comment by xeor** [comment]
@durd check the pr, works for me :)

**Comment by xeor** [comment]
Would be nice if you also could test, so @Swiftnesses can merge it..

@Swiftnesses anything else I need to do? Or does it look fine?

**Comment by Swiftnesses** [comment]
PR looks good to me guys... Apologies for the silence, new house, 2 small kids, no time... :(

**Comment by durd** [comment]
You guys are quick! :)
Just went to bed though so earliest test for me would be tomorrow evening
(CET).

**Comment by durd** [comment]
Alright!
Definitely not a complete test, but after figuring out that there was a new option to enable HTTPS and that I needed the full URL as you mentioned @xeor. I was able to turn off and on some lights with HTTPS set to `Required` on the Plex server :D 👍 

I'm not sure what is possible and not with Athoms SDK and nodejs, but I thought of an enhancement that could make things easier for users and @Swiftnesses.
I noticed (also when I first created this issue) that part of the URL `.<my-hash>.plex.direct` is included in the certificate as CN and SAN that is outputted as an error in the debug when just using the IP-address.
A further enhancement would be to error out and collect and build the URL based on the IP provided and use that. Probably should keep the IP in the textbox, but also show the URL in a greyed out box.

This would save @Swiftnesses from creating instructions and have support on how to obtain this URL, but also test if HTTPS is required and to use that if so, without the enable option. And not if not, or a logic for Plex' `Preffered` option.
More time for the house and family :)

As I said, I'm not sure what can and can't be done, so feel free to ignore the suggestion :)

Either way, I approve of the PR 👍 A slight caveat that there might be a need for an instruction for users.

**Comment by xeor** [comment]
I'm not sure if it is that easy to figure out that unique address if you just have the plex ip. Checking the SAN based on what certificate is served on that port is an option, but that complicates things a lot. And it also probably introduces some problems.

Other systems that have similar "talk to plex" needs does it like this. Introduces a checkbox. However, the docs can be better :p

What is the best way to figure out that address? I think writing a couple of sentences about it in the doc would be sufficient. Maybe a tiny FAQ?

Glad it worked for you without any problems! I do miss a way to notify users on errors tho.. But I kept this PR as simple as possible.. Error notifications is a completely different function.

**Comment by xeor** [comment]
Updated the PR with info about how to obtain the plex-address..
